#Metadata
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: main.app

- url: /
  static_files: /index.html
  upload: /index.html

#Libraries
libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest
