#Metadata
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: main.app

- url: /(.*\.(gif|png|jpg))$
  static_files: static/\1
  upload: static/.*\.(gif|png|jpg)$

#Libraries
libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest
