#Metadata
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: main.app

- url: /
  static_files: www/index.html
  upload: www/index.html

- url: /style
  static_files: /style/stylesheet.css
  upload: /style/stylesheet.css

- url: /(.*)
  static_files: www/\1
  upload: www/(.*)

#Libraries
libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest
